// Generated by scripts/sync-appstore.mjs - do not edit by hand.
// Source: https://itunes.apple.com/lookup?id=6785997584
// Last synced: 2026-08-16T21:40:08.904Z

export const APP_STORE = {
  "name": "PrivaMesh Messenger",
  "seller": "Roni Blinder",
  "bundleId": "com.privamesh",
  "version": "1.0",
  "minimumOsVersion": "26.5",
  "price": "0",
  "formattedPrice": "Free",
  "currency": "USD",
  "primaryGenre": "Social Networking",
  "contentRating": "17+",
  "releasedAt": "2026-08-06T07:00:00Z",
  "updatedAt": "2026-08-07T02:15:23Z",
  "languages": [
    "EN",
    "RU"
  ]
} as const
